### ISSUE TITLE
(blur.so) is not a valid chunkwm plugin!

### ISSUE THREAD

**Issue by 31j** [splintah/blur#17]
### (blur.so) is not a valid chunkwm plugin!

Not sure exactly why this is happening? I've tried the brew formuale as well as building from source so I am kind of confused, not sure what I have done to cause this???

_MacOS High Sierra 10.13.16 MacBook Air7,2_

**Comment by splintersuidman** [comment]
I suspect one of two things (assuming you've installed the latest version of blur, v0.2.3): you have either installed a chunkwm version before v0.4.0, or you have installed a chunkwm version later than or equal to v0.4.6.
Both v0.4.0 and v0.4.6 made ABI changes, which invalidates plugins.

If you've installed chunkwm before v0.4.0, I'd suggest to update chunkwm.

If you've installed chunkwm later than or equal to v0.4.6, it's my fault you cannot use blur; I haven't yet updated the chunkwm dependency to v0.4.6 (which I'm going to do now!, so try blur v0.2.4).

Otherwise, I don't know what could be the problem, but please share the versions of both chunkwm and blur.

**Comment by 31j** [comment]
```
chunkwm stable 0.4.6
```
Well I guess that explains the issue, I vaugely remember how the various functions worked and the ABI version that you have to build against, but yea that problem then is the version of chunkwm I'm using (never thought of the version being an issue, thank you)

Best of luck with updating blur!

**Comment by splintersuidman** [comment]
It’s already updated :), just update with Homebrew!

**Comment by 31j** [comment]
Thank you!
